### PR TITLE
Fix to organise arrow functions with methods close #16

### LINKED ISSUE #16: Arrow function methods not recognised
Thanks for the feature to support control of member ordering.  Works great, but I have found one issue that spoils it a bit.

If I define a member as an arrow function, as needed to maintain this context when creating event handlers etc, it is not recognised as a method instead it is organised as a property.  This causes a violation of tslint member-order rule with the following message:

_Declaration of public instance field not allowed after declaration of public instance method. Instead, this should come at the beginning of the class/interface_

I had a look at the source code and it looks like the problem might be with TypeScript not recognising the member as a method.  So not sure if you can do anything about it but would appreciate you taking a look.

I have attached a screen shot to help understand the problem. 
 
image

### PR DESCRIPTION
**Pull request by testpossessed**
Changed transformer.ts so that it does an additional check when it is analysing the source tree and encounters a PropertyDeclaration.  These have further information include an *initializer* property, which if populated has a *kind* property.  If this is equivalent to SyntaxKind.ArrowFunction the member is added to the methods collection rather than the properties collection, and subsequently is organised along with methods.

### CODE REVIEW

**Comment by aljazsim** [comment]
I've made some improvements to your branch, like adding a new configuration for arrow function properties to be treated as methods (false by default). Thanks for the contribution Mike!

**Comment by testpossessed** [comment]
That's great thanks.

I did consider adding a configuration option, but was a bit reluctant to go to far with changes.

**Comment by testpossessed** [comment]
Now I am using this change I see that the arrow function methods are not separated by a line.  I am happy to make a change and submit a new PR.  Would you prefer a new setting for separating these method-properties?

**Comment by aljazsim** [comment]
That would be great. Thanks Mike. I don't think a new setting is needed for this though.

**Pull request merged**
